#!/bin/bash
#This is a wrapper for the python script, to give it a pidfile, thus allowing it to be monitored and controlled through Monit

PIDFILE=/var/run/SCRIPT_NAME.pid

case $1 in
   start)
       # Launch your program as a detached process
       python /scripts/main.py &>/dev/null &
       # Get its PID and store it
       echo $! > ${PIDFILE}
   ;;
   stop)
      kill `cat ${PIDFILE}`
      # Now that it's killed, don't forget to remove the PID file
      rm ${PIDFILE}
   ;;
   *)
      echo "Usage: SCRIPT_NAME {start|stop}" ;;
esac
exit 0
